export { Header } from "./Header/Header";
export { Main } from "./Main/Main";
export { Footer } from "./Footer/Footer";
export { Container } from "./Container/Container";
export { Slider } from "./Slider/Slider";
export { SliderWrapper } from "./Slider/SliderWrapper";
export { ItemCard } from "./ItemCard/ItemCard";
export { SaleCard } from "./SaleCard/SaleCard";
export { Sortby } from "./Sortby/Sortby";
export { Price } from "./Price/Price";
export { Sizes } from "./Sizes/Sizes";
export { LazyImg } from "./LazyImg/LazyImg";
export { CategoriesList } from "./CategoriesList/CategoriesList";
export { CategoryPageRedict } from "./CategoryPageRedict/CategoryPageRedict";
export { CategoriesNav } from "./CategoriesNav/CategoriesNav";
export { Menu } from "./Menu/Menu";
export { dataFetch } from "../utils/wrapPromise";
export { MainPage, Catalog, ItemPage } from "../pages/index";
